// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20190410104228_SetNullableImagePreviewForPost")]
    partial class SetNullableImagePreviewForPost
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 10,
                            Body = "Odio earum expedita eos magnam voluptas quia aut ipsum.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(1617),
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(2611)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 17,
                            Body = "Illum et neque facilis.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(3483),
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(3498)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 8,
                            Body = "Ullam magnam quis nemo eum dolor quaerat eum.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(3603),
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(3610)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 16,
                            Body = "Fugiat delectus aspernatur soluta sit sed provident nostrum et.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(3691),
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(3698)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 6,
                            Body = "Modi in officiis itaque et et quas.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(3759),
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(3766)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            Body = "Reiciendis quia perspiciatis et quidem.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(3830),
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(3836)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 3,
                            Body = "Et accusamus ea voluptatem harum dolorem eaque eos ducimus fuga.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(3906),
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(3913)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 16,
                            Body = "Rerum iure libero voluptatem.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(3983),
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(3990)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 3,
                            Body = "Possimus dolor fugiat modi voluptatum rem doloribus necessitatibus dolores.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4056),
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4063)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 19,
                            Body = "Recusandae molestias eius ipsa sit.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4120),
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4126)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 18,
                            Body = "Ut commodi sed aut ratione saepe sed doloremque.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4188),
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4194)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 4,
                            Body = "Et assumenda sint labore voluptatem eaque dolor nulla neque quia.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4281),
                            PostId = 1,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4289)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 8,
                            Body = "Quisquam vero unde et qui.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4350),
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4356)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 21,
                            Body = "Repellendus quibusdam earum qui.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4420),
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4427)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 2,
                            Body = "Culpa enim a.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4479),
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4486)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 19,
                            Body = "Asperiores corrupti quam enim.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4538),
                            PostId = 1,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4544)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 16,
                            Body = "Inventore dolor provident.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4593),
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4599)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 13,
                            Body = "Nesciunt nostrum ut unde corporis rem reprehenderit libero quia ut.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4665),
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4672)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 2,
                            Body = "Sunt odit voluptatem saepe eius.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4725),
                            PostId = 15,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4732)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 18,
                            Body = "Est consequatur consequuntur eum.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4880),
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 524, DateTimeKind.Local).AddTicks(4888)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 8,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 539, DateTimeKind.Local).AddTicks(9429),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(424),
                            UserId = 8
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 12,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1237),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1250),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 20,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1291),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1296),
                            UserId = 11
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 17,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1326),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1331),
                            UserId = 16
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 7,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1356),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1361),
                            UserId = 13
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 16,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1385),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1390),
                            UserId = 13
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 5,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1414),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1418),
                            UserId = 16
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 12,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1443),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1448),
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 5,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1476),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1481),
                            UserId = 20
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 7,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1505),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1510),
                            UserId = 15
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 16,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1534),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1538),
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 18,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1563),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1567),
                            UserId = 9
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 1,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1614),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1620),
                            UserId = 10
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 20,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1646),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1651),
                            UserId = 9
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 2,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1678),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1682),
                            UserId = 12
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 7,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1707),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1711),
                            UserId = 18
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 1,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1735),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1740),
                            UserId = 18
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 4,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1763),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1768),
                            UserId = 9
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 4,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1791),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1796),
                            UserId = 15
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 2,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1825),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 540, DateTimeKind.Local).AddTicks(1830),
                            UserId = 17
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("URL");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 288, DateTimeKind.Local).AddTicks(1098),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/belyaev_rs/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 288, DateTimeKind.Local).AddTicks(9343)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(576),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/bpartridge/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(590)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(630),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/martip07/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(636)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(668),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/ricburton/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(674)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(697),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/sreejithexp/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(702)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(725),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/longlivemyword/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(730)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(754),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/ajaxy_ru/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(759)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(782),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/kalmerrautam/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(787)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(817),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/gonzalorobaina/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(822)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(844),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/vitor376/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(850)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(872),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/baumannzone/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(877)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(900),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/andreas_pr/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(905)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(928),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/rtgibbons/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(933)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(963),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/timothycd/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(968)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(991),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/adobi/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(996)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(1231),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/moynihan/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(1240)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(1282),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/weavermedia/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(1288)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(1312),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/nvkznemo/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(1317)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(1340),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/exentrich/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(1345)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(1369),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/cbracco/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 289, DateTimeKind.Local).AddTicks(1374)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(906),
                            URL = "https://picsum.photos/640/480/?image=392",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(1980)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2289),
                            URL = "https://picsum.photos/640/480/?image=425",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2301)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2335),
                            URL = "https://picsum.photos/640/480/?image=784",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2340)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2365),
                            URL = "https://picsum.photos/640/480/?image=758",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2370)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2392),
                            URL = "https://picsum.photos/640/480/?image=726",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2397)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2419),
                            URL = "https://picsum.photos/640/480/?image=866",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2423)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2445),
                            URL = "https://picsum.photos/640/480/?image=557",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2450)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2471),
                            URL = "https://picsum.photos/640/480/?image=263",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2475)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2498),
                            URL = "https://picsum.photos/640/480/?image=60",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2503)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2593),
                            URL = "https://picsum.photos/640/480/?image=222",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2599)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2625),
                            URL = "https://picsum.photos/640/480/?image=201",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2630)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2651),
                            URL = "https://picsum.photos/640/480/?image=217",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2656)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2678),
                            URL = "https://picsum.photos/640/480/?image=730",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2682)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2705),
                            URL = "https://picsum.photos/640/480/?image=1061",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2709)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2731),
                            URL = "https://picsum.photos/640/480/?image=52",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2736)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2758),
                            URL = "https://picsum.photos/640/480/?image=467",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2762)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2784),
                            URL = "https://picsum.photos/640/480/?image=385",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2788)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2810),
                            URL = "https://picsum.photos/640/480/?image=19",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2814)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2836),
                            URL = "https://picsum.photos/640/480/?image=341",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2840)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2862),
                            URL = "https://picsum.photos/640/480/?image=685",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 295, DateTimeKind.Local).AddTicks(2866)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("PreviewId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 14,
                            Body = "molestiae",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 514, DateTimeKind.Local).AddTicks(4538),
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 514, DateTimeKind.Local).AddTicks(5593)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 9,
                            Body = @"Nisi quia sunt sapiente sapiente quia maiores iure.
Non rerum pariatur rem id autem.
Accusantium iure odio et possimus.
Rerum illum ut unde sed qui aperiam corrupti.
Et enim repellendus dolor inventore inventore unde cupiditate tempore.
Aut possimus temporibus pariatur at voluptas dolor minima.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 516, DateTimeKind.Local).AddTicks(5149),
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 516, DateTimeKind.Local).AddTicks(5171)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 9,
                            Body = "Sapiente itaque fuga sed ad.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 516, DateTimeKind.Local).AddTicks(7346),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 516, DateTimeKind.Local).AddTicks(7361)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 20,
                            Body = "sed",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 516, DateTimeKind.Local).AddTicks(7457),
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 516, DateTimeKind.Local).AddTicks(7464)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 17,
                            Body = @"Est nihil id corporis voluptatum eos voluptas.
Tenetur delectus pariatur ut.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 516, DateTimeKind.Local).AddTicks(7654),
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 516, DateTimeKind.Local).AddTicks(7663)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 18,
                            Body = "Rem aspernatur excepturi et.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 516, DateTimeKind.Local).AddTicks(7754),
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 516, DateTimeKind.Local).AddTicks(7761)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 19,
                            Body = @"Iste aut et qui qui consequatur ipsa aut minima.
Ea perspiciatis aliquam.
Voluptate occaecati id voluptatibus expedita nobis nemo officiis harum quisquam.
Aut pariatur ut molestiae ut.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 516, DateTimeKind.Local).AddTicks(7926),
                            PreviewId = 37,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 516, DateTimeKind.Local).AddTicks(7933)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 16,
                            Body = "sint",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 516, DateTimeKind.Local).AddTicks(7985),
                            PreviewId = 39,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 516, DateTimeKind.Local).AddTicks(7992)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 4,
                            Body = "vitae",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 516, DateTimeKind.Local).AddTicks(8036),
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 516, DateTimeKind.Local).AddTicks(8042)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 21,
                            Body = "Cumque reiciendis et numquam sit aut explicabo sunt et. Quo deleniti nobis voluptatum eveniet dolor sunt a aut vel. Labore quos voluptas.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(1677),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(1693)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 1,
                            Body = @"Voluptatum dolores officiis qui aperiam recusandae quod minus.
Libero dolores sit eligendi reiciendis delectus vel eaque.
Ad aliquam corporis recusandae.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(1890),
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(1899)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 8,
                            Body = "Corrupti corporis voluptatum sit dignissimos est. Iure ea sapiente laboriosam et perspiciatis nesciunt quae et quis. Quae voluptatem voluptatem non hic cumque voluptas vel. Ut perspiciatis exercitationem. Ex quia totam magnam et amet corrupti est est. Officia natus quam optio culpa minus aspernatur quaerat accusantium.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(2146),
                            PreviewId = 39,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(2154)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 21,
                            Body = @"Sapiente ex omnis quam.
Id sunt voluptas.
Explicabo voluptatibus dignissimos.
Et laborum quisquam.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(2261),
                            PreviewId = 37,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(2268)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 11,
                            Body = "Tempore delectus non consequatur sit est voluptatem.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(2455),
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(2464)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 1,
                            Body = "Dolorum optio ut nostrum beatae velit et.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(2541),
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(2547)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 7,
                            Body = "maxime",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(2591),
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(2597)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 17,
                            Body = @"Consectetur est nemo fugit ea exercitationem a non.
Dolorem assumenda ut quam qui corrupti voluptas qui error commodi.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(2709),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(2716)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 16,
                            Body = @"Minus ex odio aliquid molestiae.
Sed nostrum quae doloribus eum odio quia.
Ipsum quia quod id exercitationem.
Rerum fugiat quia esse impedit.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(2846),
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(2853)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 19,
                            Body = "Pariatur in aut alias eum alias. Est id voluptatum fuga deleniti amet et facere quae. Totam reprehenderit ipsa. Quasi voluptatem veniam.",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(2984),
                            PreviewId = 34,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(2991)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 11,
                            Body = "voluptatem",
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(3034),
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 517, DateTimeKind.Local).AddTicks(3041)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(2442),
                            IsLike = true,
                            PostId = 1,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(3481),
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4462),
                            IsLike = true,
                            PostId = 1,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4478),
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4526),
                            IsLike = true,
                            PostId = 16,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4531),
                            UserId = 17
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4560),
                            IsLike = true,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4565),
                            UserId = 16
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4592),
                            IsLike = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4597),
                            UserId = 19
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4624),
                            IsLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4628),
                            UserId = 11
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4655),
                            IsLike = true,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4660),
                            UserId = 12
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4685),
                            IsLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4690),
                            UserId = 17
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4715),
                            IsLike = true,
                            PostId = 13,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4720),
                            UserId = 15
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4744),
                            IsLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4749),
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4773),
                            IsLike = true,
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4778),
                            UserId = 4
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4812),
                            IsLike = true,
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4818),
                            UserId = 20
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4843),
                            IsLike = true,
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4848),
                            UserId = 15
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4873),
                            IsLike = false,
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4878),
                            UserId = 6
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4904),
                            IsLike = true,
                            PostId = 4,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4909),
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4933),
                            IsLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4938),
                            UserId = 10
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4962),
                            IsLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4967),
                            UserId = 18
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4991),
                            IsLike = true,
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(4996),
                            UserId = 21
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(5021),
                            IsLike = true,
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(5026),
                            UserId = 13
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(5049),
                            IsLike = true,
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 533, DateTimeKind.Local).AddTicks(5054),
                            UserId = 20
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Expires");

                    b.Property<string>("Token");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Salt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 354, DateTimeKind.Local).AddTicks(9279),
                            Email = "Eleanore78@hotmail.com",
                            Password = "JwhgJRWNi9KZ6HvsVC4o3ATXPKrIl6NpFs14Ywn6XcQ=",
                            Salt = "1ZKXAVI9IEeT90K/cc4u5/9FM9h5NSvHrOT3p8VVgXk=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 355, DateTimeKind.Local).AddTicks(557),
                            UserName = "Reanna.Berge"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 362, DateTimeKind.Local).AddTicks(6332),
                            Email = "Noel37@gmail.com",
                            Password = "Ov/w2Ir6JjrZM+lrZWDJZQdRTyrjeX3kkEV1sNq5DLM=",
                            Salt = "81E5KuSfD6Wy6OFVRVrzJi2uxOmPDeOHy31ZANgLikw=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 362, DateTimeKind.Local).AddTicks(6356),
                            UserName = "Trevion.Konopelski"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 370, DateTimeKind.Local).AddTicks(1374),
                            Email = "Tyree.Hettinger5@hotmail.com",
                            Password = "IFV9xQIA/JkXs2hSSZbxmkQc94MfDE6An6s8rISbMYo=",
                            Salt = "lt+NT9Cw+2mitIPEmnHcp4xH3eoNtuwBukz7l2yl2Rg=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 370, DateTimeKind.Local).AddTicks(1394),
                            UserName = "Raoul_Armstrong"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 377, DateTimeKind.Local).AddTicks(6273),
                            Email = "Landen82@gmail.com",
                            Password = "pel2LSd08C+t2mEhX1uBO7rVCWTaKiAjkqj43O1ytxo=",
                            Salt = "W/OnJ8Ygem16yrXzV3ijvpYdye+/hgN2MeIiz/j9spM=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 377, DateTimeKind.Local).AddTicks(6291),
                            UserName = "Tamara_Heaney59"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 385, DateTimeKind.Local).AddTicks(1240),
                            Email = "Ashlee_Walker@gmail.com",
                            Password = "Ty1WmblkkeeehqZtK993rkptymgJ4HHmP3FtlQwggTQ=",
                            Salt = "xmkPKualMGfdZNrMieig0XspCqfUdXIsiM9n+hH0BNM=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 385, DateTimeKind.Local).AddTicks(1258),
                            UserName = "April.Baumbach63"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 392, DateTimeKind.Local).AddTicks(4481),
                            Email = "Vern_Yost17@hotmail.com",
                            Password = "UrtG6PTWOuZN01Y0wJW2RXzWQztXetNZKLMXY2kPapU=",
                            Salt = "nI8AsOHQ9rdpquComXIuzdUI83EJA5Ebtk53tHp8okM=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 392, DateTimeKind.Local).AddTicks(4494),
                            UserName = "Jessy_Trantow70"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 400, DateTimeKind.Local).AddTicks(1588),
                            Email = "Octavia.Breitenberg15@gmail.com",
                            Password = "JEPtNmc+xcRh6dRMz0XpW3YjPfo70dx6ghqpRbR7qZ8=",
                            Salt = "QkAvLRdlO782y7r9/FQ5BeOVYPCV2OixVUgbJ0x0kZQ=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 400, DateTimeKind.Local).AddTicks(1618),
                            UserName = "Brionna_Huel"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 407, DateTimeKind.Local).AddTicks(5516),
                            Email = "Jaida.Robel@yahoo.com",
                            Password = "2sM5eXjzXM4rit4n0XznRgPXWrMUrkM2NEYIt8wWdM0=",
                            Salt = "uZISArgxWHVs5sNqC3KY/zSN2GC6+cQ4PbSZXd2tY/w=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 407, DateTimeKind.Local).AddTicks(5528),
                            UserName = "Idella67"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 415, DateTimeKind.Local).AddTicks(286),
                            Email = "Merle3@hotmail.com",
                            Password = "vPqcCQvAy3m0ApPP9wTVPS+S6M+kffrzhI0KKY5byUE=",
                            Salt = "73Y6XFrs5GNfbX3gEPnUriXG+09YbIzyLCyKeTM4d/4=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 415, DateTimeKind.Local).AddTicks(305),
                            UserName = "Francesca_McClure"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 422, DateTimeKind.Local).AddTicks(5128),
                            Email = "Destin87@gmail.com",
                            Password = "3OzL76X0wfbkPwt7JQPH+/ebvc9xfBO3bcFQunQ0v4c=",
                            Salt = "E4foLxFiXVPkgaoQ+Tr6Ge0g6OSnwWDa3eNX3Y0ExT4=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 422, DateTimeKind.Local).AddTicks(5147),
                            UserName = "Ben.Legros80"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 430, DateTimeKind.Local).AddTicks(2390),
                            Email = "Finn84@gmail.com",
                            Password = "izsFaOQN3vHcHSvx8GGNmww7cWdIFOMBLISdizTYcw8=",
                            Salt = "QwJmN2g2pIq3vU+epDXifJpLcfBOM84mE8O97MdJkzg=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 430, DateTimeKind.Local).AddTicks(2408),
                            UserName = "Claudie_Von90"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 437, DateTimeKind.Local).AddTicks(7089),
                            Email = "Brady24@yahoo.com",
                            Password = "fvm+iVG/i1teAwJu6gjd99cM3VzEf33Q4lZmpYa3gtA=",
                            Salt = "qwNd4zHDb4xaQdyEy9lNs/c4y5rsfGTbauvyVwf8COc=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 437, DateTimeKind.Local).AddTicks(7102),
                            UserName = "Bertha_Kuhic"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 445, DateTimeKind.Local).AddTicks(471),
                            Email = "Amira84@yahoo.com",
                            Password = "OO/o8dRJNQHE/Cy5SsMuUoV59W4CfSqsYA1JYbnBbKA=",
                            Salt = "BcFPRW2kgTsEIJrwMiZMtEJGYYttXjV8hE2B6jCKgSQ=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 445, DateTimeKind.Local).AddTicks(482),
                            UserName = "Roxane.Bechtelar"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 452, DateTimeKind.Local).AddTicks(5168),
                            Email = "Reagan_Gottlieb96@gmail.com",
                            Password = "8/CAtMOKHMOIgZYZyjfPyFgxlGUPh2TRexcrWcVuKR0=",
                            Salt = "N4HTAz9evQh9HSBh4Ui10gobECk9Re8EzmJd04m9PKc=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 452, DateTimeKind.Local).AddTicks(5186),
                            UserName = "Willow84"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 460, DateTimeKind.Local).AddTicks(40),
                            Email = "Dane_Toy25@hotmail.com",
                            Password = "5ksghg+QRIoR4HCwib/D71e6GWEgIzgvHUy+/jIU8u4=",
                            Salt = "YHCWI8ogFKXeVnbDjONhQnBcwOv9KTCv65i5aPHgxy4=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 460, DateTimeKind.Local).AddTicks(52),
                            UserName = "Lyric_Powlowski"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 467, DateTimeKind.Local).AddTicks(7399),
                            Email = "Clyde.Kunze@gmail.com",
                            Password = "jN562rlj3Y4M9JiXhpaq22V9r5A0MCACnb8p5a03L24=",
                            Salt = "PDjMLphnPnJG54zhHoLXWCW2Jr4kTqmaumBZuqRp0GM=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 467, DateTimeKind.Local).AddTicks(7433),
                            UserName = "Kevon45"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 475, DateTimeKind.Local).AddTicks(6227),
                            Email = "Chanel.Champlin68@hotmail.com",
                            Password = "AH5M8V4Q25IYweo/q/iVqQQ4h/xed8dxtZE0aeS5cWM=",
                            Salt = "73owabAASkyG0Dvg2TnKlvWRX0FzS0ur49Ur3J5H3qM=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 475, DateTimeKind.Local).AddTicks(6272),
                            UserName = "Jewell_Schmitt"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 483, DateTimeKind.Local).AddTicks(1289),
                            Email = "Watson.Bahringer@yahoo.com",
                            Password = "Q62jzI0XYrLxW7Vfi/yI+uS4YjSlRcUbQZxMQGfc8C0=",
                            Salt = "vSbXm9StFleAMjE1o2oRvdW3lJHYt7hkHrsLCa7Dg4U=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 483, DateTimeKind.Local).AddTicks(1302),
                            UserName = "Jazmin98"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 490, DateTimeKind.Local).AddTicks(5812),
                            Email = "Aditya.Kerluke@yahoo.com",
                            Password = "7D2UgGVDo4CTiK0CFT/Cd2Kryi7caZwemc5a7f9Xus8=",
                            Salt = "zUsIM0NUWcyfmuUZWfbZD/ip+Wl+JZe/hLUSru5/rSM=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 490, DateTimeKind.Local).AddTicks(5824),
                            UserName = "Josefa_Brakus"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 498, DateTimeKind.Local).AddTicks(265),
                            Email = "Stewart.Kiehn@hotmail.com",
                            Password = "huLmL4GntVXBmnUFICkmowedAskr5IoAk5wW5424zqQ=",
                            Salt = "AmgoIHeRfU91KKABVopqN9E6rEyTLpgLW9RqszTP2zc=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 498, DateTimeKind.Local).AddTicks(276),
                            UserName = "Margaretta_Schaden"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 505, DateTimeKind.Local).AddTicks(3866),
                            Email = "test@gmail.com",
                            Password = "C+XvvutUOnUo6U86oKynPexTPQkkhKfd4pYAf+LzYPE=",
                            Salt = "wBQhcRU+Nh0iNrhTwxtzwOXjMhOxlLTx5BkVJ3h6sB4=",
                            UpdatedAt = new DateTime(2019, 4, 10, 13, 42, 27, 505, DateTimeKind.Local).AddTicks(3866),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");
                });
#pragma warning restore 612, 618
        }
    }
}
