// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20190402150830_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 19,
                            Body = "Fuga qui aut qui vel et dolores pariatur eos.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 898, DateTimeKind.Local).AddTicks(4923),
                            PostId = 13,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 898, DateTimeKind.Local).AddTicks(4923)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 15,
                            Body = "Quia dolores et.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(5459),
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(5459)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 19,
                            Body = "Excepturi reiciendis quidem aut.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(5680),
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(5680)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 6,
                            Body = "Rerum non eos voluptatem omnis impedit perspiciatis.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(5744),
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(5744)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            Body = "Natus delectus hic.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(5808),
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(5808)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 17,
                            Body = "Eaque fuga ut modi explicabo laudantium eligendi quam error commodi.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(5860),
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(5860)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 5,
                            Body = "Consequuntur occaecati tempora et tempora iusto reprehenderit repellat officia nemo.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(5938),
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(5938)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 10,
                            Body = "Est autem labore facere rem sequi nulla sit animi.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6071),
                            PostId = 13,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6071)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 4,
                            Body = "Velit deleniti quo quisquam cumque.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6144),
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6144)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 6,
                            Body = "Quia ex animi suscipit ut est officia.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6197),
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6197)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 4,
                            Body = "Ipsam ab nesciunt magnam id ipsam.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6252),
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6252)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 6,
                            Body = "Soluta dicta sint cupiditate ipsa in aliquid vel tenetur iste.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6303),
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6303)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 8,
                            Body = "Nisi qui occaecati.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6427),
                            PostId = 16,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6427)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 15,
                            Body = "Ea maxime error similique inventore voluptatem neque animi odit neque.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6479),
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6479)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 16,
                            Body = "Necessitatibus ullam consectetur cupiditate ea fugiat iste.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6549),
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6549)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 6,
                            Body = "Quidem quisquam soluta natus adipisci impedit impedit qui consequatur ut.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6604),
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6604)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 18,
                            Body = "Fugit occaecati eos quis.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6664),
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6664)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 20,
                            Body = "Et non eaque id.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6708),
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6708)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 3,
                            Body = "Molestiae fugit sed eius.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6808),
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6808)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 20,
                            Body = "Non pariatur autem deserunt delectus necessitatibus qui et autem.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6859),
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 899, DateTimeKind.Local).AddTicks(6859)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 14,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 914, DateTimeKind.Local).AddTicks(4119),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 914, DateTimeKind.Local).AddTicks(4119),
                            UserId = 16
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 12,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1498),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1498),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 2,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1647),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1647),
                            UserId = 10
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 18,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1679),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1679),
                            UserId = 10
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 16,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1703),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1703),
                            UserId = 16
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 15,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1724),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1724),
                            UserId = 7
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 2,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1799),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1799),
                            UserId = 11
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 16,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1823),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1823),
                            UserId = 7
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 6,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1844),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1844),
                            UserId = 8
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 1,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1867),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1867),
                            UserId = 7
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 12,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1909),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1909),
                            UserId = 4
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 16,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1983),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(1983),
                            UserId = 8
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 11,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(2007),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(2007),
                            UserId = 15
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 20,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(2029),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(2029),
                            UserId = 11
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 18,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(2051),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(2051),
                            UserId = 18
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 16,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(2073),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(2073),
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 3,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(2093),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(2093),
                            UserId = 8
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 17,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(2114),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(2114),
                            UserId = 5
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 10,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(2135),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(2135),
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 13,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(2156),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 915, DateTimeKind.Local).AddTicks(2156),
                            UserId = 14
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("URL");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 851, DateTimeKind.Local).AddTicks(8476),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/g3d/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 851, DateTimeKind.Local).AddTicks(8476)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3449),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/johnsmithagency/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3449)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3638),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/hiemil/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3638)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3667),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/shesgared/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3667)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3686),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/uxpiper/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3686)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3703),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/anatolinicolae/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3703)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3721),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/borantula/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3721)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3737),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/jeremyshimko/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3737)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3754),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/geshan/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3754)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3770),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/devankoshal/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3770)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3786),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/mattlat/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3786)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3801),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/codysanfilippo/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3801)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3817),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/jonathansimmons/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3817)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3833),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/iqbalperkasa/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3833)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3848),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/jcubic/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3848)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3867),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/zauerkraut/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3867)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3882),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/syropian/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3882)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3897),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/plasticine/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3897)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3912),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/teylorfeliz/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3912)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3926),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/kolsvein/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 864, DateTimeKind.Local).AddTicks(3926)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 868, DateTimeKind.Local).AddTicks(3159),
                            URL = "https://picsum.photos/640/480/?image=104",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 868, DateTimeKind.Local).AddTicks(3159)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3438),
                            URL = "https://picsum.photos/640/480/?image=497",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3438)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3511),
                            URL = "https://picsum.photos/640/480/?image=563",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3511)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3531),
                            URL = "https://picsum.photos/640/480/?image=478",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3531)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3548),
                            URL = "https://picsum.photos/640/480/?image=740",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3548)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3565),
                            URL = "https://picsum.photos/640/480/?image=771",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3565)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3581),
                            URL = "https://picsum.photos/640/480/?image=277",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3581)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3658),
                            URL = "https://picsum.photos/640/480/?image=1081",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3658)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3680),
                            URL = "https://picsum.photos/640/480/?image=1060",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3680)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3697),
                            URL = "https://picsum.photos/640/480/?image=404",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3697)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3714),
                            URL = "https://picsum.photos/640/480/?image=1017",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3714)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3730),
                            URL = "https://picsum.photos/640/480/?image=583",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3730)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3745),
                            URL = "https://picsum.photos/640/480/?image=402",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3745)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3761),
                            URL = "https://picsum.photos/640/480/?image=613",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3761)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3776),
                            URL = "https://picsum.photos/640/480/?image=392",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3776)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3792),
                            URL = "https://picsum.photos/640/480/?image=109",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3792)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3808),
                            URL = "https://picsum.photos/640/480/?image=727",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3808)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3823),
                            URL = "https://picsum.photos/640/480/?image=498",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3823)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3838),
                            URL = "https://picsum.photos/640/480/?image=946",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3838)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3854),
                            URL = "https://picsum.photos/640/480/?image=708",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 869, DateTimeKind.Local).AddTicks(3854)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("PreviewId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 17,
                            Body = @"Hic eos omnis consequatur.
Quo saepe natus quidem.
Deserunt ipsa sapiente ut optio aut rem molestiae eos eius.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 888, DateTimeKind.Local).AddTicks(8294),
                            PreviewId = 30,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 888, DateTimeKind.Local).AddTicks(8294)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 18,
                            Body = "velit",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 891, DateTimeKind.Local).AddTicks(9946),
                            PreviewId = 39,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 891, DateTimeKind.Local).AddTicks(9946)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Body = @"Excepturi a nesciunt recusandae corrupti quis odio voluptatum minima quae.
Deleniti fugit voluptatem facere aut sit.
Et ea aliquid molestiae id.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(689),
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(689)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 11,
                            Body = "Aliquid rerum ea dolorem expedita id consequuntur a. Odit voluptatum soluta quaerat et consectetur. Ducimus quod consequatur perspiciatis voluptatum odio.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(1010),
                            PreviewId = 39,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(1010)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            Body = "debitis",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(3936),
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(3936)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 14,
                            Body = "Sint qui qui aut quia.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(4006),
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(4006)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 3,
                            Body = "qui",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(5676),
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(5676)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 7,
                            Body = "Et qui aut pariatur ut tempora velit ad reprehenderit animi. Voluptates reiciendis qui repellat. Alias ipsa est dolores consectetur maxime sed qui autem. Optio quia et vero ea cum eveniet asperiores cum. Omnis facere pariatur consequuntur aut.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(5723),
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(5723)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 17,
                            Body = @"Esse eos dolore quae.
Aspernatur consectetur voluptate quisquam sed veniam est.
Odio non quia ex provident velit.
Perferendis voluptatibus qui facilis alias dolore.
Deleniti magnam perspiciatis voluptate.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(6021),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(6021)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 20,
                            Body = "vel",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(6496),
                            PreviewId = 37,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(6496)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 17,
                            Body = "Corrupti quos ad natus quasi. Minima voluptate mollitia cum. Aut nisi dolorem velit et. Animi ipsa quaerat et impedit sequi quia impedit.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(6536),
                            PreviewId = 26,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(6536)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 18,
                            Body = "Eligendi dolore deleniti.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(6781),
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(6781)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 4,
                            Body = "Qui in officiis ut repellendus aut in aliquam. Et rerum sapiente rerum fugit ea fugiat. In dolor suscipit. Pariatur repellendus quis. Ut et et consequatur dolorum qui ipsum soluta est dolores.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(6858),
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(6858)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 13,
                            Body = "Dolorem culpa et.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(7082),
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(7082)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 12,
                            Body = "aliquid",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(7132),
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(7132)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 7,
                            Body = "Quos non sit. Id autem qui consequatur iusto reiciendis ratione. Voluptatibus sed totam veniam modi voluptatibus. Distinctio aut minima a possimus. Quod voluptatem sunt laborum.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(7162),
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(7162)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 15,
                            Body = @"A sapiente dolores fugit in incidunt officia.
Est nulla iusto voluptatum consequuntur.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(7350),
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(7350)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 12,
                            Body = "saepe",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(7436),
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(7436)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 8,
                            Body = "Aliquam molestiae et asperiores. Dolores qui sed et animi minima qui et. Temporibus odit culpa aut quasi cupiditate officia. Quia cumque et.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(7467),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(7467)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 19,
                            Body = @"Asperiores quia et maxime nihil quasi soluta ea.
Explicabo rerum atque adipisci fugiat adipisci tempore.
Modi veniam temporibus sit.",
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(7641),
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 892, DateTimeKind.Local).AddTicks(7641)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 906, DateTimeKind.Local).AddTicks(5856),
                            IsLike = true,
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 906, DateTimeKind.Local).AddTicks(5856),
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1179),
                            IsLike = true,
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1179),
                            UserId = 11
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1336),
                            IsLike = false,
                            PostId = 16,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1336),
                            UserId = 16
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1367),
                            IsLike = true,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1367),
                            UserId = 9
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1390),
                            IsLike = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1390),
                            UserId = 12
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1411),
                            IsLike = false,
                            PostId = 13,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1411),
                            UserId = 16
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1430),
                            IsLike = false,
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1430),
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1452),
                            IsLike = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1452),
                            UserId = 7
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1472),
                            IsLike = false,
                            PostId = 16,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1472),
                            UserId = 10
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1492),
                            IsLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1492),
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1513),
                            IsLike = true,
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1513),
                            UserId = 17
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1533),
                            IsLike = true,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1533),
                            UserId = 11
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1552),
                            IsLike = true,
                            PostId = 12,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1552),
                            UserId = 19
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1576),
                            IsLike = true,
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1576),
                            UserId = 11
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1595),
                            IsLike = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1595),
                            UserId = 12
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1615),
                            IsLike = true,
                            PostId = 1,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1615),
                            UserId = 9
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1659),
                            IsLike = false,
                            PostId = 13,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1659),
                            UserId = 7
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1738),
                            IsLike = false,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1738),
                            UserId = 11
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1761),
                            IsLike = true,
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1761),
                            UserId = 10
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1781),
                            IsLike = false,
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 908, DateTimeKind.Local).AddTicks(1781),
                            UserId = 7
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvatarId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 875, DateTimeKind.Local).AddTicks(8202),
                            Email = "Ena71@gmail.com",
                            Password = "Ykta0p3j",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 875, DateTimeKind.Local).AddTicks(8202),
                            UserName = "Jon.Hoppe"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(5286),
                            Email = "Clyde46@hotmail.com",
                            Password = "kMdcqBC2",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(5286),
                            UserName = "Lucius12"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(5899),
                            Email = "Travis_Orn25@yahoo.com",
                            Password = "rIQMu8t1",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(5899),
                            UserName = "Eleanora74"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(6088),
                            Email = "Gregorio_Hettinger@hotmail.com",
                            Password = "qdfNRCD1",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(6088),
                            UserName = "Sarah_Von72"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(6301),
                            Email = "Paul_Bosco1@yahoo.com",
                            Password = "oFaePi37",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(6301),
                            UserName = "Dasia1"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(6431),
                            Email = "Lela_Schmidt@hotmail.com",
                            Password = "OcY7QhHd",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(6431),
                            UserName = "Guy_Waelchi"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(6605),
                            Email = "Joannie.Christiansen83@yahoo.com",
                            Password = "ksM16tDk",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(6605),
                            UserName = "Jeffery_Stiedemann90"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(6798),
                            Email = "Vicente75@yahoo.com",
                            Password = "6RBimjs1",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(6798),
                            UserName = "Major_Crooks"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(6983),
                            Email = "Eugene82@gmail.com",
                            Password = "06MJIRXF",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(6983),
                            UserName = "Oral.Harvey"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(7115),
                            Email = "Cullen47@yahoo.com",
                            Password = "gAiqI6LH",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(7115),
                            UserName = "Christina.Prosacco96"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(7288),
                            Email = "Eda.Bergstrom78@gmail.com",
                            Password = "MFAXZThC",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(7288),
                            UserName = "Lawrence.Corwin51"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(7425),
                            Email = "Marilyne8@hotmail.com",
                            Password = "hG35chpF",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(7425),
                            UserName = "Astrid.Johnson"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(7602),
                            Email = "Ashleigh.Kunde@hotmail.com",
                            Password = "rR5wowmT",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(7602),
                            UserName = "Genevieve.Mante68"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(7727),
                            Email = "Winona_Hagenes@gmail.com",
                            Password = "EcB7pQ6g",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(7727),
                            UserName = "Aimee_Dooley7"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(7844),
                            Email = "Shaun20@hotmail.com",
                            Password = "dz1r35Nk",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(7844),
                            UserName = "Larue_Kris"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(8013),
                            Email = "Anna74@hotmail.com",
                            Password = "WkSw14l1",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(8013),
                            UserName = "Braeden.Reichert16"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(8142),
                            Email = "Jared16@yahoo.com",
                            Password = "mAmrecut",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(8142),
                            UserName = "Hattie67"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(8309),
                            Email = "Alfred_Gorczany5@yahoo.com",
                            Password = "RKfonEhf",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(8309),
                            UserName = "Dannie_Macejkovic"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(8435),
                            Email = "Stuart68@gmail.com",
                            Password = "34UcXcu1",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(8435),
                            UserName = "Helen84"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(8630),
                            Email = "Celestine30@hotmail.com",
                            Password = "67Cu_ULu",
                            UpdatedAt = new DateTime(2019, 4, 2, 18, 8, 29, 882, DateTimeKind.Local).AddTicks(8630),
                            UserName = "Eleanora_Grady"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
