// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20190608103002_AddCommentReactionAlternateKey")]
    partial class AddCommentReactionAlternateKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 16,
                            Body = "Et minus amet.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(961),
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(2177)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 12,
                            Body = "Sit sint architecto.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(4079),
                            PostId = 13,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(4119)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 8,
                            Body = "Ea ad deleniti ut quis officia voluptatibus occaecati.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(4379),
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(4399)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 17,
                            Body = "In eius qui necessitatibus et sapiente quis iure.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(4626),
                            PostId = 16,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(4642)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 8,
                            Body = "Dolor doloremque est rerum et quis.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(4837),
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(4853)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 19,
                            Body = "Tenetur occaecati omnis dolorem molestiae.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(5039),
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(5056)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 11,
                            Body = "Ut tempore ut id et odit temporibus.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(5295),
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(5315)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 18,
                            Body = "Qui iste temporibus dolores.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(5494),
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(5514)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 19,
                            Body = "Dolores ducimus magni qui nesciunt est quia aut a tempore.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(5729),
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(5749)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 19,
                            Body = "Delectus non nihil cumque sed dolores ut impedit.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(5952),
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(5972)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 10,
                            Body = "Consequuntur odit tempora omnis vel sunt illum nobis et quia.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(6195),
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(6211)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 17,
                            Body = "At aut veritatis veritatis.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(6402),
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(6418)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 2,
                            Body = "Voluptates inventore libero sit illo pariatur.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(6657),
                            PostId = 1,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(6677)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 9,
                            Body = "Quam magnam quidem cupiditate ratione id ab eum.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(6904),
                            PostId = 4,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(6925)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 13,
                            Body = "At adipisci expedita dignissimos provident architecto.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(7119),
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(7135)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 19,
                            Body = "Architecto deleniti earum.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(7285),
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(7302)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 15,
                            Body = "Quasi iusto ipsa.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(7460),
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(7480)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 21,
                            Body = "Aut maiores eum a quibusdam non.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(7837),
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(7861)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 13,
                            Body = "Soluta est animi.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(8072),
                            PostId = 12,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(8092)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 20,
                            Body = "In tempora et voluptatibus ut et consequatur fuga.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(8287),
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 827, DateTimeKind.Local).AddTicks(8303)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasAlternateKey("CommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 11,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 865, DateTimeKind.Local).AddTicks(6993),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 865, DateTimeKind.Local).AddTicks(8315),
                            UserId = 21
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 18,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 865, DateTimeKind.Local).AddTicks(9981),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(9),
                            UserId = 6
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 14,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(115),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(127),
                            UserId = 18
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 18,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(208),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(224),
                            UserId = 15
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 18,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(305),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(321),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 8,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(402),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(419),
                            UserId = 14
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 10,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(504),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(520),
                            UserId = 12
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 1,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(666),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(682),
                            UserId = 19
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 3,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(779),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(796),
                            UserId = 16
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 13,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(881),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(897),
                            UserId = 15
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 18,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(978),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(994),
                            UserId = 5
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 20,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(1079),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(1096),
                            UserId = 9
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 6,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(1185),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(1197),
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 18,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(1282),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(1298),
                            UserId = 7
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 20,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(1379),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(1396),
                            UserId = 13
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 4,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(1797),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(1821),
                            UserId = 12
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 17,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(1915),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(1931),
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 7,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(2008),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(2024),
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 2,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(2101),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(2113),
                            UserId = 10
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 11,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(2190),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 866, DateTimeKind.Local).AddTicks(2202),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("URL");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 425, DateTimeKind.Local).AddTicks(742),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/exentrich/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(2661)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(5920),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/kolage/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(5952)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6046),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/joshaustin/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6058)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6127),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/yecidsm/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6143)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6212),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/aoimedia/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6224)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6293),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/jonkspr/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6305)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6374),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/mutlu82/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6386)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6459),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/mgonto/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6471)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6540),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/karalek/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6552)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6621),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/igorgarybaldi/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6633)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6698),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/alek_djuric/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6715)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6779),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/renbyrd/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6796)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6860),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/mahmoudmetwally/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6873)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6942),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/mattdetails/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(6954)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(7019),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/baumann_alex/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(7035)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(7100),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/kuldarkalvik/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(7116)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(7181),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/motionthinks/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(7193)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(7258),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/urrutimeoli/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(7270)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(7339),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/wesleytrankin/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(7355)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(7420),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/timmillwood/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 426, DateTimeKind.Local).AddTicks(7436)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(539),
                            URL = "https://picsum.photos/640/480/?image=393",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(1638)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2112),
                            URL = "https://picsum.photos/640/480/?image=1079",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2141)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2218),
                            URL = "https://picsum.photos/640/480/?image=801",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2234)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2299),
                            URL = "https://picsum.photos/640/480/?image=951",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2315)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2376),
                            URL = "https://picsum.photos/640/480/?image=436",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2392)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2457),
                            URL = "https://picsum.photos/640/480/?image=64",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2473)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2538),
                            URL = "https://picsum.photos/640/480/?image=436",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2550)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2639),
                            URL = "https://picsum.photos/640/480/?image=243",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2656)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2720),
                            URL = "https://picsum.photos/640/480/?image=515",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2733)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2797),
                            URL = "https://picsum.photos/640/480/?image=290",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2814)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2879),
                            URL = "https://picsum.photos/640/480/?image=400",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2891)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2956),
                            URL = "https://picsum.photos/640/480/?image=839",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(2972)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(3037),
                            URL = "https://picsum.photos/640/480/?image=926",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(3053)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(3118),
                            URL = "https://picsum.photos/640/480/?image=163",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(3130)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(3195),
                            URL = "https://picsum.photos/640/480/?image=455",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(3207)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(3272),
                            URL = "https://picsum.photos/640/480/?image=688",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(3284)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(3349),
                            URL = "https://picsum.photos/640/480/?image=759",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(3361)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(3430),
                            URL = "https://picsum.photos/640/480/?image=307",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(3442)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(3507),
                            URL = "https://picsum.photos/640/480/?image=488",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(3523)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(3584),
                            URL = "https://picsum.photos/640/480/?image=902",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 439, DateTimeKind.Local).AddTicks(3600)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("PreviewId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 4,
                            Body = "Enim ea sunt eos reprehenderit maxime.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 808, DateTimeKind.Local).AddTicks(9179),
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 809, DateTimeKind.Local).AddTicks(346)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 16,
                            Body = @"Exercitationem assumenda expedita eos possimus dolorem aut repellat eos.
Error voluptate molestiae et laudantium.
Explicabo ea est totam soluta esse cumque voluptatibus qui voluptatem.
Ex corrupti praesentium omnis vitae occaecati.
Dicta doloribus qui vero sit incidunt id aspernatur ipsum.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 810, DateTimeKind.Local).AddTicks(4781),
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 810, DateTimeKind.Local).AddTicks(4826)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 11,
                            Body = "Non placeat asperiores qui. Quis qui aut. Tempore iste dolores.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 810, DateTimeKind.Local).AddTicks(9731),
                            PreviewId = 34,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 810, DateTimeKind.Local).AddTicks(9760)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 6,
                            Body = @"Atque rerum consequuntur illum rem quia labore.
Vel eos qui et sunt.
Officia aspernatur magnam molestiae.
Laudantium a voluptatibus ut expedita sed et ratione.
Cupiditate unde vitae officia quos.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(307),
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(323)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 10,
                            Body = "aperiam",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(1361),
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(1389)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 7,
                            Body = @"Quisquam nihil natus quidem dolores iusto.
Qui et aspernatur est numquam harum et est totam et.
Accusantium itaque vel eum dolor asperiores placeat.
Aut voluptatum et.
Ut neque impedit voluptatum voluptatem vel aspernatur error nihil.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(1941),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(1957)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 18,
                            Body = "sed",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(2131),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(2147)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 19,
                            Body = "Voluptas praesentium similique et voluptates unde illum libero necessitatibus facilis.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(2387),
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(2403)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 5,
                            Body = "Quos voluptas mollitia magni est quas.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(2581),
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(2597)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            Body = "Consequuntur ipsam est. Quo autem dolor rem quia quia perferendis et. Inventore laborum saepe. Quis dolorem provident cum a dolore voluptas et occaecati.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(3027),
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(3047)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 6,
                            Body = "Dolorum adipisci facere repellendus incidunt quia maiores. Pariatur iure esse nisi. Voluptatum eum error quasi repellat. Aliquid et tempore quo quis dolorem quasi. Aut consectetur itaque aut optio quis soluta qui corporis.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(3530),
                            PreviewId = 26,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(3550)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 21,
                            Body = "Qui adipisci voluptatem ratione voluptatem laborum doloribus commodi.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(3741),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(3757)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 13,
                            Body = "In distinctio hic ex. Et neque dignissimos odit maiores repudiandae. Quisquam ut in vitae non minima.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(4065),
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(4081)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 21,
                            Body = "Aliquid eligendi aut omnis vitae in et ut. Voluptas provident aut sit. Hic ut et eius et quo. Voluptate minus ut facilis. Veniam dignissimos cum doloribus deserunt et.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(4523),
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(4539)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 14,
                            Body = @"Et vitae ipsa velit facere.
Est consectetur asperiores natus rerum culpa autem qui in.
Illum totam rerum a similique voluptates libero sed.
Iste neque ipsum quis odit doloremque.
Quis harum officia dolores sed sint blanditiis facilis dicta.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(5058),
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(5074)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 16,
                            Body = "Corporis nulla adipisci natus ab occaecati et nihil cumque. Velit et id adipisci. Deleniti ut necessitatibus provident autem nostrum maxime. Voluptatem deleniti corporis perferendis ullam officiis eius. Qui voluptatum mollitia aliquam voluptatem.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(5545),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(5561)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 13,
                            Body = "molestias",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(5674),
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(5690)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 5,
                            Body = "Minima omnis quaerat ab est ducimus omnis voluptatem. Sunt iste nostrum non vitae placeat molestias ex eum. Saepe deserunt dignissimos qui earum minima. Quia fugiat voluptatem id quo illum sed.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(6116),
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(6132)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 12,
                            Body = @"Ut assumenda et et.
Voluptatem optio doloremque ipsa rerum nemo repellat quo.
Dignissimos ut magni fugiat quidem voluptatem est aut enim.
Ullam et eos quod ipsum reprehenderit rerum tempora possimus aut.
Porro reprehenderit explicabo illum sed et dolore.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(6643),
                            PreviewId = 30,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(6659)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 16,
                            Body = @"Sapiente quis culpa velit commodi rerum iusto voluptatum neque.
Sunt sed eum nesciunt a vero.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(6931),
                            PreviewId = 34,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 811, DateTimeKind.Local).AddTicks(6943)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasAlternateKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(465),
                            IsLike = false,
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(1693),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(3452),
                            IsLike = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(3485),
                            UserId = 13
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(3606),
                            IsLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(3623),
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(3716),
                            IsLike = true,
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(3728),
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(3809),
                            IsLike = true,
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(3821),
                            UserId = 16
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(3906),
                            IsLike = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(3918),
                            UserId = 13
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4004),
                            IsLike = true,
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4020),
                            UserId = 18
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4097),
                            IsLike = true,
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4113),
                            UserId = 20
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4186),
                            IsLike = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4198),
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4275),
                            IsLike = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4287),
                            UserId = 15
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4364),
                            IsLike = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4381),
                            UserId = 8
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4458),
                            IsLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4470),
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4543),
                            IsLike = false,
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4559),
                            UserId = 16
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4632),
                            IsLike = true,
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4644),
                            UserId = 20
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4721),
                            IsLike = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4733),
                            UserId = 12
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4806),
                            IsLike = true,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4822),
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4904),
                            IsLike = false,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(4916),
                            UserId = 15
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(5001),
                            IsLike = true,
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(5017),
                            UserId = 5
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(5098),
                            IsLike = false,
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(5114),
                            UserId = 10
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(5199),
                            IsLike = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 848, DateTimeKind.Local).AddTicks(5216),
                            UserId = 19
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Expires");

                    b.Property<string>("Token");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Salt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 498, DateTimeKind.Local).AddTicks(4064),
                            Email = "Lewis66@yahoo.com",
                            Password = "ipp+S75e/5LiuvKBM0nZrEQsP+7SMRMzqcaRN08Npeo=",
                            Salt = "euuwrkqYzcRNJGdeN7pEtbfzLCvqO+eavPQlg+vBgT4=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 498, DateTimeKind.Local).AddTicks(5085),
                            UserName = "Berta.Mann13"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 510, DateTimeKind.Local).AddTicks(8861),
                            Email = "Zula.Schultz0@gmail.com",
                            Password = "P8ThNsvBpgNPvmH1YqSUD2/vtQRDH/Lul3MQa1elkRI=",
                            Salt = "oI1mrCZQsTc837g5oIG3HMPEvL9DrfDpegteKB4mOas=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 510, DateTimeKind.Local).AddTicks(8946),
                            UserName = "Emiliano_Rice44"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 523, DateTimeKind.Local).AddTicks(1692),
                            Email = "Reagan60@yahoo.com",
                            Password = "0seLIYhjNnliKhex2dDOLL/USB49B2vjmm35kPNClV0=",
                            Salt = "2VgpQTnja97w2gvln6xsIeJnhGCvbckR1fahcmznjBw=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 523, DateTimeKind.Local).AddTicks(1773),
                            UserName = "Keely_Johnston"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 535, DateTimeKind.Local).AddTicks(2230),
                            Email = "Keon.Lang62@yahoo.com",
                            Password = "6U7+IRUGC7b0o9gvk13Hmjq7fqhQrz5LUeBrI7N8KFc=",
                            Salt = "yfVqUaYEqo8GpvMHeBTVWEvVt8tbqBlOg6RdI2UT4os=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 535, DateTimeKind.Local).AddTicks(2311),
                            UserName = "Odell91"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 547, DateTimeKind.Local).AddTicks(4604),
                            Email = "Itzel.Hintz@yahoo.com",
                            Password = "NuSFkBsHxCG6xLWi69+t4D0QQGJ6BVVhb9xbXZLdvuw=",
                            Salt = "RhFEqCkXU6TJ/PlnhiUc1oPhH+KaEWnNBGn83ls6cpI=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 547, DateTimeKind.Local).AddTicks(4685),
                            UserName = "Elmore_Zieme78"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 563, DateTimeKind.Local).AddTicks(166),
                            Email = "Lonie68@hotmail.com",
                            Password = "9kzThCD61VguYbsRHNtsljedbZNR1l25iA5h7tnglD4=",
                            Salt = "urBn05zOW2W/z0SRh+ROKzQA8zstGURtGXA8s6Vb2a4=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 563, DateTimeKind.Local).AddTicks(255),
                            UserName = "Alanis58"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 578, DateTimeKind.Local).AddTicks(2826),
                            Email = "Kristin97@gmail.com",
                            Password = "0V7MfOMBFz35VAxpeLP/VykoHmFr7Y6TMb7KmCsI/aY=",
                            Salt = "7sMIRbE3J8XKIl6X9jKvzdPbJKIBm2ObprWHVvqbjCg=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 578, DateTimeKind.Local).AddTicks(3337),
                            UserName = "Mallory.Lowe"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 591, DateTimeKind.Local).AddTicks(1073),
                            Email = "Brock.Morissette45@yahoo.com",
                            Password = "W0C3ON2PXLVca3hpSsshp9A731PcJZ/uhs6iqIEPNO0=",
                            Salt = "rfSm1BxD/Cz3A0fKq9SM3lViajI8Rf0JUblIsycGTHk=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 591, DateTimeKind.Local).AddTicks(1166),
                            UserName = "Adrian47"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 603, DateTimeKind.Local).AddTicks(309),
                            Email = "Chester.Botsford18@hotmail.com",
                            Password = "TD3rl13TivQ0isdJJdv3otUiNVS1qu95yZQACMf2xlw=",
                            Salt = "D+kG+ztr9Id+AD59gxJdJygPRlt/ioTnMqMBlmFDyjE=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 603, DateTimeKind.Local).AddTicks(394),
                            UserName = "Alysha_Kovacek"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 617, DateTimeKind.Local).AddTicks(9451),
                            Email = "Marcelina62@yahoo.com",
                            Password = "aLjZF/bDcOOeW7qCP9dwuSPumeOm9QRufFkUKft46+4=",
                            Salt = "bh5Ft5t/KbW9P4fmQXyGpy+XgKou4wo7+Rdd1ySJm8Y=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 617, DateTimeKind.Local).AddTicks(9552),
                            UserName = "Rupert_Kassulke55"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 639, DateTimeKind.Local).AddTicks(2043),
                            Email = "Shaylee79@yahoo.com",
                            Password = "Rh0T1eDmyKZIDhDBfPV7+xzjf1K+T84PENeigQVqr+E=",
                            Salt = "bYVeC1RbOLLbVVmDf1eTE1dAGCKYfgEgYbNWtgYNIyk=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 639, DateTimeKind.Local).AddTicks(2132),
                            UserName = "Gwendolyn_Boehm"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 661, DateTimeKind.Local).AddTicks(877),
                            Email = "Mauricio.Von33@yahoo.com",
                            Password = "UTni2loimGZ5Kti93HaEZ+fciZCwfO/ZaPOc44RxhhM=",
                            Salt = "cYSMaR0B14+YVoFvlt8tjpPoZY2z5K5jIFb2xsHfxZs=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 661, DateTimeKind.Local).AddTicks(966),
                            UserName = "Coleman_Bosco95"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 673, DateTimeKind.Local).AddTicks(2489),
                            Email = "Elton.Farrell22@hotmail.com",
                            Password = "DSLPWWQIc4TRCSD6QevyvmOV2Q8UikaYj+CawmvEYhM=",
                            Salt = "Nd3AGdFKVWNX6lV8EepGfNXRRTrIbZt+crUIxwN7K4A=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 673, DateTimeKind.Local).AddTicks(2582),
                            UserName = "Delores_Hauck92"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 685, DateTimeKind.Local).AddTicks(5677),
                            Email = "Sabryna13@hotmail.com",
                            Password = "2I1TP1TVsZiysC0zeVLdGzmL6bsTG5Yro1ZMoZPOVZs=",
                            Salt = "2ttqWS2Z+EZN+C1+MQpRFtwsg1kh/bqEJOhp5GaQdo0=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 685, DateTimeKind.Local).AddTicks(5778),
                            UserName = "Lucie32"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 702, DateTimeKind.Local).AddTicks(7746),
                            Email = "Ardith.Cummings95@yahoo.com",
                            Password = "XKm4g0rS/kMzXDlq1A0xd0Mj1UTKz78QZqEIjGiVzaI=",
                            Salt = "joVmnahae87VaRCkiCZANdQn93d2cMmII5sssUek7AQ=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 702, DateTimeKind.Local).AddTicks(7844),
                            UserName = "Benton99"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 724, DateTimeKind.Local).AddTicks(7786),
                            Email = "Wilfrid54@yahoo.com",
                            Password = "dymXvZziyvE784wDCRRuv+Kazm4duf2yUAZQJG9MFzw=",
                            Salt = "6iWfzQsuyR5S7/Xx02k+yJV5y6UWvnNU4rUmZYTba58=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 724, DateTimeKind.Local).AddTicks(7875),
                            UserName = "Shaylee.King"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 741, DateTimeKind.Local).AddTicks(6309),
                            Email = "Harold.Rowe71@yahoo.com",
                            Password = "LoU3WAtUBJTUjad+UJqki5rZ6n/M9omgb/3+yVk7vMw=",
                            Salt = "n/uUFtMkyUefMnQNz/j6Vaqzr/osn7pBREHzWM8lIU8=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 741, DateTimeKind.Local).AddTicks(6406),
                            UserName = "Cali.Waters"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 753, DateTimeKind.Local).AddTicks(8333),
                            Email = "Samanta_OReilly95@yahoo.com",
                            Password = "+YA8dDK1ZoLFTvfpnVQGzmhKXHRaAgN/fQjmZMVMGcM=",
                            Salt = "Bhn9S4MMVApZjnGJUamRVV4ikTzCgdc/KBbTMldMsjY=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 753, DateTimeKind.Local).AddTicks(8426),
                            UserName = "Baylee_Sipes42"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 765, DateTimeKind.Local).AddTicks(8563),
                            Email = "Rex64@hotmail.com",
                            Password = "JOICOM6OozRPh4VLEbxS/iJMsI1HhHyOdDtuG4tau78=",
                            Salt = "EdoXXUo+awEKlbwKaH/IFKIzz1Ybyl69YYeYJACQ/nM=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 765, DateTimeKind.Local).AddTicks(8648),
                            UserName = "Sharon32"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 779, DateTimeKind.Local).AddTicks(1504),
                            Email = "Brice_Abshire72@gmail.com",
                            Password = "D+HiHDuS3LIsqdZUuSEQeZ0VSpvsWiTYTKiW1JwGMPU=",
                            Salt = "unJ1mBlcdh5pmmYITwm9s49RsQknqWgoUYsqdrOvjbI=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 779, DateTimeKind.Local).AddTicks(1590),
                            UserName = "Kayla46"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 791, DateTimeKind.Local).AddTicks(1782),
                            Email = "test@gmail.com",
                            Password = "i2TJ0z00NYlgYE1RckEz65RuduHNOi6XLzkY/zjls3M=",
                            Salt = "OfXWhBQuNh3ZiHzV/LYq5X7zvFdI56jXiAJ/cQcbvJM=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 30, 1, 791, DateTimeKind.Local).AddTicks(1782),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");
                });
#pragma warning restore 612, 618
        }
    }
}
