// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20190608102411_AddPostReactionAlternateKey")]
    partial class AddPostReactionAlternateKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 4,
                            Body = "Non corrupti sint excepturi consequatur ut debitis ut.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 924, DateTimeKind.Local).AddTicks(9115),
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(27)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 17,
                            Body = "Eum optio sunt architecto.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(1300),
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(1324)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 18,
                            Body = "Dolor culpa ut tempora.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(1466),
                            PostId = 1,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(1474)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 6,
                            Body = "Aut nam nulla quaerat.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(1572),
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(1580)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 7,
                            Body = "Voluptatem et minima sed id et.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(1673),
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(1681)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 20,
                            Body = "Perferendis magnam magnam quia exercitationem in eveniet.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(1807),
                            PostId = 12,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(1815)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 8,
                            Body = "Odit est eum ut corporis facilis accusamus.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(1908),
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(1920)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 7,
                            Body = "Aperiam quo et molestias omnis ea harum.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2014),
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2022)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 8,
                            Body = "Aut vero voluptatem inventore.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2099),
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2107)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 6,
                            Body = "Molestiae et deleniti voluptas ut tempore quidem.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2200),
                            PostId = 16,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2212)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 7,
                            Body = "Porro reiciendis necessitatibus minus excepturi eum nemo corrupti.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2301),
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2309)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 9,
                            Body = "Ea recusandae assumenda id ea in mollitia magnam.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2419),
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2427)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 11,
                            Body = "Voluptas ab earum.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2504),
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2512)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 10,
                            Body = "Magni eaque ut tempora ut est repudiandae ipsam est.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2609),
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2618)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 20,
                            Body = "Tenetur similique aperiam harum pariatur similique.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2699),
                            PostId = 15,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2711)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 8,
                            Body = "Et enim ipsa doloremque.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2780),
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2792)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 2,
                            Body = "Et voluptas temporibus voluptatem recusandae totam ea voluptatem.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2881),
                            PostId = 11,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2889)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 17,
                            Body = "Non vero quis possimus hic aut.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2990),
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(2999)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 5,
                            Body = "Reiciendis optio velit autem natus id cum harum voluptas.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(3096),
                            PostId = 4,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(3108)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 11,
                            Body = "Velit quia nam aut distinctio voluptatum ut.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(3193),
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 925, DateTimeKind.Local).AddTicks(3201)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 16,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(7307),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(8252),
                            UserId = 6
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 1,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9460),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9480),
                            UserId = 7
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 11,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9565),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9573),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 5,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9622),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9630),
                            UserId = 17
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 20,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9675),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9683),
                            UserId = 7
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 12,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9727),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9735),
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 19,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9776),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9784),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 16,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9829),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9837),
                            UserId = 20
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 18,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9881),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9885),
                            UserId = 13
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 19,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9930),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 953, DateTimeKind.Local).AddTicks(9934),
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 17,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(133),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(145),
                            UserId = 18
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 11,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(202),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(206),
                            UserId = 15
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 20,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(250),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(258),
                            UserId = 9
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 18,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(303),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(311),
                            UserId = 17
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 8,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(352),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(360),
                            UserId = 19
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 1,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(404),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(412),
                            UserId = 9
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 5,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(453),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(461),
                            UserId = 14
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 7,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(506),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(514),
                            UserId = 14
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 7,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(554),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(562),
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 15,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(607),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 954, DateTimeKind.Local).AddTicks(615),
                            UserId = 21
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("URL");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 589, DateTimeKind.Local).AddTicks(3877),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/jnmnrd/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(4620)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(6760),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/ripplemdk/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(6780)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(6841),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/depaulawagner/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(6849)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(6889),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/romanbulah/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(6897)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(6934),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/kushsolitary/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(6942)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(6983),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/elliotlewis/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(6991)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7027),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/akmur/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7035)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7072),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/maxlinderman/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7080)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7120),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/conspirator/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7128)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7165),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/thewillbeard/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7173)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7210),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/gipsy_raf/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7218)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7254),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/batsirai/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7262)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7331),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/rtgibbons/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7339)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7376),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/dmackerman/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7384)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7424),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/salvafc/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7432)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7469),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/marshallchen_/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7477)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7518),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/hanna_smi/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7526)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7562),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/arindam_/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7570)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7611),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/franciscoamk/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7619)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7655),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/codysanfilippo/128.jpg",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 590, DateTimeKind.Local).AddTicks(7664)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(3720),
                            URL = "https://picsum.photos/640/480/?image=382",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(4737)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5171),
                            URL = "https://picsum.photos/640/480/?image=100",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5187)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5232),
                            URL = "https://picsum.photos/640/480/?image=728",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5240)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5503),
                            URL = "https://picsum.photos/640/480/?image=445",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5520)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5572),
                            URL = "https://picsum.photos/640/480/?image=768",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5580)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5613),
                            URL = "https://picsum.photos/640/480/?image=436",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5621)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5657),
                            URL = "https://picsum.photos/640/480/?image=580",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5665)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5702),
                            URL = "https://picsum.photos/640/480/?image=92",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5710)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5742),
                            URL = "https://picsum.photos/640/480/?image=389",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5751)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5787),
                            URL = "https://picsum.photos/640/480/?image=247",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5795)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5828),
                            URL = "https://picsum.photos/640/480/?image=1022",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5836)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5872),
                            URL = "https://picsum.photos/640/480/?image=1055",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5876)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5913),
                            URL = "https://picsum.photos/640/480/?image=437",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5921)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5953),
                            URL = "https://picsum.photos/640/480/?image=195",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5961)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(5998),
                            URL = "https://picsum.photos/640/480/?image=23",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(6002)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(6140),
                            URL = "https://picsum.photos/640/480/?image=315",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(6152)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(6205),
                            URL = "https://picsum.photos/640/480/?image=1048",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(6213)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(6249),
                            URL = "https://picsum.photos/640/480/?image=703",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(6257)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(6290),
                            URL = "https://picsum.photos/640/480/?image=617",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(6298)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(6334),
                            URL = "https://picsum.photos/640/480/?image=412",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 600, DateTimeKind.Local).AddTicks(6342)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("PreviewId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 17,
                            Body = @"Laboriosam nihil dignissimos excepturi quas.
Dolore qui magnam accusamus.
Recusandae molestiae vitae quae.
Enim ut atque.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 909, DateTimeKind.Local).AddTicks(5003),
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 909, DateTimeKind.Local).AddTicks(6195)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Body = "et",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 909, DateTimeKind.Local).AddTicks(8392),
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 909, DateTimeKind.Local).AddTicks(8424)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 19,
                            Body = "voluptatem",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 909, DateTimeKind.Local).AddTicks(8680),
                            PreviewId = 34,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 909, DateTimeKind.Local).AddTicks(8696)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 11,
                            Body = "Aut fuga nobis architecto ab accusantium consectetur qui. Necessitatibus eos assumenda est distinctio assumenda excepturi velit quia itaque. Ab repudiandae occaecati. Fuga itaque ducimus voluptatum ipsum. Impedit totam voluptatibus sint sapiente ullam qui. Maiores quis ipsa laboriosam rerum necessitatibus consectetur aperiam vero ea.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(3529),
                            PreviewId = 26,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(3573)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 16,
                            Body = "Nulla temporibus nobis inventore aut in qui fugit.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(6350),
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(6383)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 18,
                            Body = "Qui repellendus dolores optio. Fugit tempora modi et illo impedit. Et aspernatur officia vitae quae. Distinctio eos ipsa dolorum.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(6820),
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(6837)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 3,
                            Body = "Occaecati officiis impedit voluptas commodi ut nihil quibusdam dolore quisquam. Temporibus qui tempora ducimus adipisci minus reiciendis dolor. Ullam eos doloremque provident quas ipsam.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(7453),
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(7481)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 15,
                            Body = "Autem ad fugit nihil ut. Qui nisi consequatur molestiae corporis nisi commodi nisi nihil voluptatem. Deserunt molestiae praesentium at quia quisquam optio distinctio nulla quia. Ab eaque error voluptatem expedita esse voluptates sint minima. Aspernatur magnam consequatur harum omnis unde repellat.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(8235),
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(8260)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 7,
                            Body = "beatae",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(8385),
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(8401)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 20,
                            Body = @"Qui tempore omnis quam.
Quas assumenda et.
Ut ea minima nobis hic.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(8924),
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(8953)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 16,
                            Body = "Quia qui eius ut ipsum optio. Quia maiores maxime repellat. Sit cum non sapiente ut sapiente eos deleniti. Atque aut laboriosam consequatur consectetur quisquam quo.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(9403),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(9427)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 2,
                            Body = "et",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(9549),
                            PreviewId = 39,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(9565)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 7,
                            Body = "cum",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(9670),
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 910, DateTimeKind.Local).AddTicks(9687)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 21,
                            Body = "Ut voluptas dolor nesciunt exercitationem dolore nisi id.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 911, DateTimeKind.Local).AddTicks(205),
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 911, DateTimeKind.Local).AddTicks(230)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 20,
                            Body = "earum",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 911, DateTimeKind.Local).AddTicks(359),
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 911, DateTimeKind.Local).AddTicks(376)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 17,
                            Body = "Aut ut voluptatibus reiciendis nemo. Tempora sunt non temporibus sapiente quas. Minus voluptates qui qui in enim cumque earum ipsa. Pariatur fugit cum minus error tempora rerum. Sequi deleniti voluptas.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 911, DateTimeKind.Local).AddTicks(992),
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 911, DateTimeKind.Local).AddTicks(1016)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 6,
                            Body = "Mollitia accusamus iste qui consequatur praesentium vel aspernatur.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 911, DateTimeKind.Local).AddTicks(1251),
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 911, DateTimeKind.Local).AddTicks(1268)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 21,
                            Body = "Voluptatibus voluptas et doloribus voluptate.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 911, DateTimeKind.Local).AddTicks(1438),
                            PreviewId = 37,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 911, DateTimeKind.Local).AddTicks(1454)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 16,
                            Body = "eos",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 911, DateTimeKind.Local).AddTicks(1563),
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 911, DateTimeKind.Local).AddTicks(1580)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 21,
                            Body = @"Omnis consequatur accusantium cupiditate vel sed sit in voluptatibus in.
Ea cum aspernatur totam.
Quis deleniti ad.",
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 911, DateTimeKind.Local).AddTicks(2070),
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 911, DateTimeKind.Local).AddTicks(2095)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasAlternateKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(1912),
                            IsLike = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(2857),
                            UserId = 12
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4138),
                            IsLike = true,
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4158),
                            UserId = 16
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4215),
                            IsLike = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4223),
                            UserId = 16
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4272),
                            IsLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4280),
                            UserId = 6
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4321),
                            IsLike = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4325),
                            UserId = 16
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4365),
                            IsLike = false,
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4373),
                            UserId = 9
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4418),
                            IsLike = true,
                            PostId = 15,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4426),
                            UserId = 17
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4467),
                            IsLike = true,
                            PostId = 7,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4475),
                            UserId = 18
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4515),
                            IsLike = false,
                            PostId = 13,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4523),
                            UserId = 17
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4564),
                            IsLike = false,
                            PostId = 6,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4572),
                            UserId = 20
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4613),
                            IsLike = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4617),
                            UserId = 5
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4657),
                            IsLike = false,
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4665),
                            UserId = 5
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4706),
                            IsLike = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4714),
                            UserId = 5
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4750),
                            IsLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4758),
                            UserId = 17
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4969),
                            IsLike = true,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(4977),
                            UserId = 7
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(5026),
                            IsLike = false,
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(5034),
                            UserId = 19
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(5075),
                            IsLike = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(5083),
                            UserId = 4
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(5123),
                            IsLike = true,
                            PostId = 14,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(5131),
                            UserId = 8
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(5168),
                            IsLike = true,
                            PostId = 15,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(5176),
                            UserId = 6
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(5217),
                            IsLike = true,
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 940, DateTimeKind.Local).AddTicks(5225),
                            UserId = 9
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Expires");

                    b.Property<string>("Token");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Salt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 649, DateTimeKind.Local).AddTicks(8537),
                            Email = "Imelda_Mitchell@hotmail.com",
                            Password = "wyS8r7yMuR/yYkZpf5BJOxg5V9qqg4UGqbMM+Pgag3E=",
                            Salt = "d3lRpJNDHy3y6QlutEp0jv53B8TOANIq/vlG5QN2bfY=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 649, DateTimeKind.Local).AddTicks(9643),
                            UserName = "Reuben.Christiansen89"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 662, DateTimeKind.Local).AddTicks(3481),
                            Email = "Nathanial_Fadel@yahoo.com",
                            Password = "UTyh4GQu9OjyCxUQIJgRn7uNifHqj18ddaAyieFubzs=",
                            Salt = "p8WXhYEGnfjAgjxwoqm4+LWluwKSbMHVqH804hivgRc=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 662, DateTimeKind.Local).AddTicks(3537),
                            UserName = "Kaya_Abshire"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 675, DateTimeKind.Local).AddTicks(2774),
                            Email = "Amy51@yahoo.com",
                            Password = "0XAVOmsGos6NYeYfA/aLk5GXkTC/lGugwyDmc3GVuxk=",
                            Salt = "9QZwjNGZmsgRslXzE551bMUPlyApp/Vw4iyBUH1W6tY=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 675, DateTimeKind.Local).AddTicks(2908),
                            UserName = "Vanessa6"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 688, DateTimeKind.Local).AddTicks(2186),
                            Email = "Chauncey7@yahoo.com",
                            Password = "P2O/2CzM5A657L1OGFHD+VDHCzJ9cCBYN2tl7RdbwRs=",
                            Salt = "fufyUMFjYHZLYY+aHzcmkG97Z5t3Dc9TAQYSSk3dlDg=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 688, DateTimeKind.Local).AddTicks(2271),
                            UserName = "Deja46"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 700, DateTimeKind.Local).AddTicks(1186),
                            Email = "Eliseo30@gmail.com",
                            Password = "JDsGalAoSUg9xBSvO2KtbAEI620GjZr7RoHrSRopwjI=",
                            Salt = "kVzmhMtXPNV3V46lUi4CgKUgMb/bP87dNmZ25VeUehI=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 700, DateTimeKind.Local).AddTicks(1222),
                            UserName = "Emie.Keeling"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 711, DateTimeKind.Local).AddTicks(9628),
                            Email = "Noemi56@hotmail.com",
                            Password = "WHmpfsxTZ4a3ki+FfZYEoXYhXzJ419KDH4vpbvHlgS4=",
                            Salt = "4TfDGaYCE5ugQdQDVp6wr4xZjNZONPLhY1J9JcjANok=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 711, DateTimeKind.Local).AddTicks(9713),
                            UserName = "Sheldon_Leffler10"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 723, DateTimeKind.Local).AddTicks(8020),
                            Email = "Kendall2@hotmail.com",
                            Password = "VYXxf4nvupXQS6Zz1Q2N76V6q3nr8M1qvNI23DelvsQ=",
                            Salt = "ftAaNGT6QbRtbPDvY8AOVnYAxk26i0U9mjoM2JOFZPc=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 723, DateTimeKind.Local).AddTicks(8065),
                            UserName = "Jeffrey.Cole18"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 735, DateTimeKind.Local).AddTicks(5554),
                            Email = "Elody.McGlynn@gmail.com",
                            Password = "89BGXQqv8APjIrKdd1LmcgWMnK2GEuf8vFiFuodfmLU=",
                            Salt = "d9K+61rDS4X4iKI2KacIHZjSeeToefvetYuY0pmRocw=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 735, DateTimeKind.Local).AddTicks(5582),
                            UserName = "Casimir.Kuvalis66"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 747, DateTimeKind.Local).AddTicks(3135),
                            Email = "Annabelle.Pfannerstill70@hotmail.com",
                            Password = "LQ1QG1OPoMELqJgtjbMWJ4jLHwz6X3C4GIVsU74ihy0=",
                            Salt = "Dtb/ilr4hTxeksCopdumegbCs1p3RkOQ3enWUr5gVwQ=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 747, DateTimeKind.Local).AddTicks(3163),
                            UserName = "Cecil31"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 759, DateTimeKind.Local).AddTicks(3778),
                            Email = "Tomasa83@hotmail.com",
                            Password = "4aUN8reXCO7XnIgBLe9bulWG9Aytr0dyz5NB0KeaMlw=",
                            Salt = "rXTAahrjJYyxxGPoID3uZv+T0+974g7uOY1yAi00YDc=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 759, DateTimeKind.Local).AddTicks(3802),
                            UserName = "Claire.Schimmel89"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 771, DateTimeKind.Local).AddTicks(3075),
                            Email = "Marcelo_Kutch57@gmail.com",
                            Password = "aPkSwOPUqajY5apaCrNq9PpIU8WgqL40Axggd6iK99E=",
                            Salt = "FQ573nSXcqf75rmGCG4x0dGJvbhDZwKLPRxp6fQ6IzI=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 771, DateTimeKind.Local).AddTicks(3124),
                            UserName = "Wyatt.Wilkinson82"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 783, DateTimeKind.Local).AddTicks(385),
                            Email = "Twila_VonRueden@gmail.com",
                            Password = "9NtWMl54l2wZstG4AyDSiAJChnhDBTX032xl0uapvY0=",
                            Salt = "sNSoVnVP2Yp1OhZtO9I2p9+12i1AswsoGjLRhGyzhho=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 783, DateTimeKind.Local).AddTicks(405),
                            UserName = "Carroll78"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 794, DateTimeKind.Local).AddTicks(7006),
                            Email = "Camylle.Kuhic19@hotmail.com",
                            Password = "PPtN9ynCvm6BmzyJmuEQ7MjPQNja5ahy+PbJz6IJRxQ=",
                            Salt = "76xYe45mt5Q85hwABGNl4hF+bkPfnuhgndSyxVRjsfM=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 794, DateTimeKind.Local).AddTicks(7026),
                            UserName = "Kip_King21"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 806, DateTimeKind.Local).AddTicks(4539),
                            Email = "Zelda34@hotmail.com",
                            Password = "4S5rujwzG/q2ADzkwQ8izczTxibwgZmZ6/FY5Xd8uX4=",
                            Salt = "cgL2Ma/TiU44ljZ75rx5aAWEYz8yZcsNjso2aToyWnU=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 806, DateTimeKind.Local).AddTicks(4572),
                            UserName = "Karlee.Wyman"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 818, DateTimeKind.Local).AddTicks(2178),
                            Email = "Carey5@gmail.com",
                            Password = "L2Z2SFAz1AyehYLHIH8vxPhqsroqNXEW9QVdAz7r2yU=",
                            Salt = "F6WiaxRQVU3kSKfLyE4BfORG6+8xUoM14C7xmUpfPxk=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 818, DateTimeKind.Local).AddTicks(2207),
                            UserName = "Jermaine_Abshire75"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 829, DateTimeKind.Local).AddTicks(9690),
                            Email = "Theodore_Hansen@yahoo.com",
                            Password = "/k18UDf/tV+SVuGXwWZ9YgRRt3T+6ADCZmwdkOyhjiQ=",
                            Salt = "MIKcgdu0Mi8ubIscY6n2DTafZ16fK3Ap++BRTM2JY6I=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 829, DateTimeKind.Local).AddTicks(9715),
                            UserName = "Lucas_Homenick"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 841, DateTimeKind.Local).AddTicks(7017),
                            Email = "Betty.Sipes@yahoo.com",
                            Password = "VZ3S8wR2Um0qYP4g95PjVPPfUgdD9pe3eNagQlJi5IA=",
                            Salt = "VWq9YflxtYqgePBtAWkMqx0TluE024suOAGe8VvmjFY=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 841, DateTimeKind.Local).AddTicks(7049),
                            UserName = "Amos_Barrows"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 854, DateTimeKind.Local).AddTicks(692),
                            Email = "Remington.Kshlerin@yahoo.com",
                            Password = "ymLk+n3xMfUG+KCKCh9ZrrMMmNKqvjs50hneHGaMUNI=",
                            Salt = "78EYRe71iMiTNOxdElqZ0s4HFzmN7YbjhfoSuTgwS/E=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 854, DateTimeKind.Local).AddTicks(716),
                            UserName = "Marta48"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 865, DateTimeKind.Local).AddTicks(8785),
                            Email = "Cathy.Farrell70@hotmail.com",
                            Password = "39WyNceHUmTJcxJiDCQxID/u/Nsu6lE09HbMlb3bc1Q=",
                            Salt = "H95PjqcgDx705qBP4ZYroF6ow8eiVLOvBlGzytba7Ro=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 865, DateTimeKind.Local).AddTicks(8809),
                            UserName = "Esteban_Lynch"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 879, DateTimeKind.Local).AddTicks(8006),
                            Email = "Dina.Kuhn49@gmail.com",
                            Password = "URkbHB7R11wL0/JYYDTkum0+Bd4zlwZCKBpy5fZPrf8=",
                            Salt = "uG4w3oyzQsKt1GUvHg1yAx5ZHhSE1pBPFHGGo5Yr7yU=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 879, DateTimeKind.Local).AddTicks(8095),
                            UserName = "Mitchell.Morar3"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 891, DateTimeKind.Local).AddTicks(4960),
                            Email = "test@gmail.com",
                            Password = "QVKpHEyoJLWG3jel9WXMt7oZZAwAByiIyMDoo9hnDGQ=",
                            Salt = "6GRVMRd5wxVCxlerTQTqzThL21t7W1A20dMYl+ebfNE=",
                            UpdatedAt = new DateTime(2019, 6, 8, 13, 24, 10, 891, DateTimeKind.Local).AddTicks(4960),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");
                });
#pragma warning restore 612, 618
        }
    }
}
