// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20190402132112_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("PostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 16,
                            Body = "Illo necessitatibus id quae illo necessitatibus placeat.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 485, DateTimeKind.Local).AddTicks(1335),
                            PostId = 15,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 485, DateTimeKind.Local).AddTicks(1335)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 10,
                            Body = "Quod cupiditate rerum eos voluptatem autem inventore ullam.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(2261),
                            PostId = 17,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(2261)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Body = "Quisquam nulla nesciunt et totam aut est minus omnis corporis.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(2536),
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(2536)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 17,
                            Body = "Eaque ducimus blanditiis non laboriosam quod repellat accusamus autem assumenda.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(2627),
                            PostId = 5,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(2627)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 12,
                            Body = "Necessitatibus esse qui rerum ut aut vero unde suscipit quae.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(2775),
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(2775)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 15,
                            Body = "Debitis voluptatem eaque non molestiae soluta quidem.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(2855),
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(2855)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 8,
                            Body = "Laboriosam provident a quo nulla vitae molestiae architecto sit.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(2918),
                            PostId = 10,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(2918)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 7,
                            Body = "Enim minima dolores.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(2988),
                            PostId = 4,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(2988)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 18,
                            Body = "Ex nihil ea.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3041),
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3041)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 13,
                            Body = "Eos reiciendis eum eos laboriosam voluptatem laborum dolore repellendus.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3092),
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3092)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 10,
                            Body = "Perferendis dolorem aut.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3269),
                            PostId = 9,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3269)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 8,
                            Body = "Magnam eaque odit possimus impedit omnis quibusdam explicabo et id.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3331),
                            PostId = 8,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3331)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 2,
                            Body = "Laudantium nihil quia at accusamus magnam.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3399),
                            PostId = 15,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3399)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 4,
                            Body = "Assumenda labore suscipit impedit.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3456),
                            PostId = 1,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3456)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 13,
                            Body = "Aut sit necessitatibus exercitationem et.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3536),
                            PostId = 2,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3536)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 8,
                            Body = "Odit ut quasi et dolore est aut eos.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3594),
                            PostId = 4,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3594)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 6,
                            Body = "Nobis consequatur ipsam qui numquam laboriosam ut quasi.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3703),
                            PostId = 18,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3703)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 10,
                            Body = "Alias mollitia est omnis corrupti qui.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3769),
                            PostId = 3,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3769)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 8,
                            Body = "Quo aliquid iste maxime id sit alias corrupti provident omnis.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3825),
                            PostId = 19,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3825)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 4,
                            Body = "Excepturi laboriosam excepturi eligendi debitis cum tenetur.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3889),
                            PostId = 12,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 486, DateTimeKind.Local).AddTicks(3889)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("ReactionId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("ReactionId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 8,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(874),
                            ReactionId = 1,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(874)
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 1,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(7851),
                            ReactionId = 7,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(7851)
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 7,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8009),
                            ReactionId = 14,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8009)
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 1,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8040),
                            ReactionId = 14,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8040)
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 3,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8061),
                            ReactionId = 6,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8061)
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 13,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8082),
                            ReactionId = 7,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8082)
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 9,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8103),
                            ReactionId = 13,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8103)
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 6,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8123),
                            ReactionId = 1,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8123)
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 5,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8142),
                            ReactionId = 6,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8142)
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 8,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8163),
                            ReactionId = 16,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8163)
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 5,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8181),
                            ReactionId = 18,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8181)
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 15,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8209),
                            ReactionId = 8,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8209)
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 3,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8312),
                            ReactionId = 11,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8312)
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 11,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8332),
                            ReactionId = 9,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8332)
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 10,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8351),
                            ReactionId = 16,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8351)
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 4,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8371),
                            ReactionId = 11,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8371)
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 13,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8391),
                            ReactionId = 7,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8391)
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 4,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8410),
                            ReactionId = 15,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8410)
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 10,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8429),
                            ReactionId = 4,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8429)
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 4,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8448),
                            ReactionId = 17,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 495, DateTimeKind.Local).AddTicks(8448)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("URL");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 414, DateTimeKind.Local).AddTicks(6772),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/okcoker/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 414, DateTimeKind.Local).AddTicks(6772)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(727),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/mateaodviteza/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(727)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(914),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/charlesrpratt/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(914)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(946),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/dhooyenga/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(946)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(969),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/sethlouey/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(969)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(989),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/s4f1/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(989)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1011),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/calebogden/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1011)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1029),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/arashmanteghi/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1029)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1047),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/bistrianiosip/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1047)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1066),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/woodsman001/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1066)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1084),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/h1brd/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1084)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1103),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/klefue/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1103)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1122),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/felipeapiress/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1122)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1139),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/leemunroe/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1139)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1161),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/lawlbwoy/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1161)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1179),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/ZacharyZorbas/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1179)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1197),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/atariboy/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1197)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1216),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/pehamondello/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1216)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1233),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/thinkleft/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1233)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1251),
                            URL = "https://s3.amazonaws.com/uifaces/faces/twitter/kojourin/128.jpg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 428, DateTimeKind.Local).AddTicks(1251)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 432, DateTimeKind.Local).AddTicks(3071),
                            URL = "https://picsum.photos/640/480/?image=894",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 432, DateTimeKind.Local).AddTicks(3071)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(4836),
                            URL = "https://picsum.photos/640/480/?image=135",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(4836)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(4907),
                            URL = "https://picsum.photos/640/480/?image=798",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(4907)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(4929),
                            URL = "https://picsum.photos/640/480/?image=1049",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(4929)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(4948),
                            URL = "https://picsum.photos/640/480/?image=373",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(4948)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(4966),
                            URL = "https://picsum.photos/640/480/?image=421",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(4966)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(4983),
                            URL = "https://picsum.photos/640/480/?image=56",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(4983)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5068),
                            URL = "https://picsum.photos/640/480/?image=655",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5068)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5089),
                            URL = "https://picsum.photos/640/480/?image=183",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5089)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5107),
                            URL = "https://picsum.photos/640/480/?image=22",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5107)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5124),
                            URL = "https://picsum.photos/640/480/?image=613",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5124)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5141),
                            URL = "https://picsum.photos/640/480/?image=764",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5141)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5159),
                            URL = "https://picsum.photos/640/480/?image=624",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5159)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5175),
                            URL = "https://picsum.photos/640/480/?image=505",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5175)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5192),
                            URL = "https://picsum.photos/640/480/?image=207",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5192)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5210),
                            URL = "https://picsum.photos/640/480/?image=976",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5210)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5227),
                            URL = "https://picsum.photos/640/480/?image=438",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5227)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5244),
                            URL = "https://picsum.photos/640/480/?image=992",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5244)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5260),
                            URL = "https://picsum.photos/640/480/?image=526",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5260)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5277),
                            URL = "https://picsum.photos/640/480/?image=906",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 433, DateTimeKind.Local).AddTicks(5277)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("PreviewId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 16,
                            Body = "quidem",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 453, DateTimeKind.Local).AddTicks(5083),
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 453, DateTimeKind.Local).AddTicks(5083)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Body = "Esse non quia molestiae quas rerum et fuga.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 455, DateTimeKind.Local).AddTicks(2601),
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 455, DateTimeKind.Local).AddTicks(2601)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 16,
                            Body = "Quisquam eos et nemo placeat earum in.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 456, DateTimeKind.Local).AddTicks(4792),
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 456, DateTimeKind.Local).AddTicks(4792)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 16,
                            Body = "Quia fuga assumenda dolores veritatis labore aspernatur doloremque. Sapiente deserunt sed doloribus veniam et est. Nesciunt eligendi sit est aliquam.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 456, DateTimeKind.Local).AddTicks(5124),
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 456, DateTimeKind.Local).AddTicks(5124)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 6,
                            Body = "Ut dolor facere et odio consequatur optio eius debitis fugit. Error officiis aut quis. Possimus perspiciatis distinctio. Laudantium ipsam pariatur vel est. Amet ut tenetur asperiores reiciendis. Consequuntur ut et at omnis aspernatur sequi.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(4284),
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(4284)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            Body = "placeat",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(4663),
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(4663)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 10,
                            Body = @"Ex consectetur officiis.
Labore et nihil sint.
Quis quaerat sequi qui quibusdam.
Rerum eos error odio cupiditate.
Sint corporis distinctio.
Laudantium accusantium ea error et minima.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(4719),
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(4719)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            Body = "perspiciatis",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(6127),
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(6127)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 14,
                            Body = @"Molestiae rerum non iure quo alias autem.
Autem et rem sed nesciunt exercitationem.
Quo necessitatibus numquam eos est deserunt voluptatem aliquid dicta explicabo.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(6178),
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(6178)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 19,
                            Body = @"Voluptas voluptate quia non animi neque doloribus.
Qui eum dicta non est cumque assumenda maxime at ipsum.
Impedit officiis et accusamus.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(6421),
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(6421)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 8,
                            Body = "Exercitationem deserunt ipsam cumque dolore quis. Et sit tempora. Est nulla ut reprehenderit voluptatum est veritatis velit. Ipsam ut reprehenderit occaecati totam perspiciatis quidem vero. Fuga perferendis optio similique unde fuga incidunt.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(6595),
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(6595)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 18,
                            Body = "Animi nihil velit fuga rem.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(6777),
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(6777)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 1,
                            Body = "Saepe at quos earum consequuntur rerum. Autem incidunt nihil est. Non nihil numquam alias. Ullam ut neque voluptate. Omnis sunt ab laborum recusandae.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(6877),
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(6877)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 7,
                            Body = "soluta",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(7053),
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(7053)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 5,
                            Body = "minus",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(7094),
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(7094)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 2,
                            Body = @"Accusantium minima nesciunt culpa tempore ea quia impedit.
Rem incidunt natus iste ex maiores.
Architecto ea necessitatibus sint aut odio maxime.
Voluptatem repudiandae ut iure.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(7131),
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(7131)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 5,
                            Body = "Libero dolores magni eos velit esse eligendi iusto tempora aliquid. Aut quia dolor maiores nesciunt eos dicta. Id et libero officia provident delectus iste omnis blanditiis. Id ea cum et nobis necessitatibus eius vero blanditiis. Doloribus velit beatae repellendus dicta ipsum reprehenderit ut id.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(7319),
                            PreviewId = 39,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(7319)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 19,
                            Body = "Nulla ut alias unde mollitia quia rerum et ut est. Doloribus eveniet sequi iusto nostrum voluptas. Nobis non vel sed eum. Et commodi in expedita voluptatem perspiciatis natus ut qui soluta. Quo necessitatibus tempore voluptatem minima incidunt suscipit sapiente molestiae. Aspernatur enim ut laudantium ducimus.",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(7624),
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(7624)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 7,
                            Body = "facere",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(7947),
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(7947)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 5,
                            Body = "fugit",
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(7987),
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 457, DateTimeKind.Local).AddTicks(7987)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("PostId");

                    b.Property<int>("ReactionId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("ReactionId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 490, DateTimeKind.Local).AddTicks(6201),
                            PostId = 16,
                            ReactionId = 17,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 490, DateTimeKind.Local).AddTicks(6201)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4076),
                            PostId = 6,
                            ReactionId = 14,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4076)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4219),
                            PostId = 6,
                            ReactionId = 10,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4219)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4248),
                            PostId = 4,
                            ReactionId = 10,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4248)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4270),
                            PostId = 8,
                            ReactionId = 9,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4270)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4291),
                            PostId = 5,
                            ReactionId = 6,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4291)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4311),
                            PostId = 7,
                            ReactionId = 17,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4311)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4331),
                            PostId = 12,
                            ReactionId = 6,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4331)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4351),
                            PostId = 1,
                            ReactionId = 11,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4351)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4373),
                            PostId = 15,
                            ReactionId = 7,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4373)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4395),
                            PostId = 11,
                            ReactionId = 11,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4395)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4415),
                            PostId = 10,
                            ReactionId = 10,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4415)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4434),
                            PostId = 2,
                            ReactionId = 10,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4434)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4460),
                            PostId = 6,
                            ReactionId = 9,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4460)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4481),
                            PostId = 15,
                            ReactionId = 16,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4481)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4501),
                            PostId = 3,
                            ReactionId = 17,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4501)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4520),
                            PostId = 6,
                            ReactionId = 16,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4520)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4539),
                            PostId = 16,
                            ReactionId = 11,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4539)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4558),
                            PostId = 7,
                            ReactionId = 2,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4558)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4578),
                            PostId = 15,
                            ReactionId = 15,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 491, DateTimeKind.Local).AddTicks(4578)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Reaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsLike");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reaction");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 464, DateTimeKind.Local).AddTicks(6080),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 464, DateTimeKind.Local).AddTicks(6080),
                            UserId = 20
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 465, DateTimeKind.Local).AddTicks(9741),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 465, DateTimeKind.Local).AddTicks(9741),
                            UserId = 14
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 465, DateTimeKind.Local).AddTicks(9906),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 465, DateTimeKind.Local).AddTicks(9906),
                            UserId = 12
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 465, DateTimeKind.Local).AddTicks(9933),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 465, DateTimeKind.Local).AddTicks(9933),
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 465, DateTimeKind.Local).AddTicks(9953),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 465, DateTimeKind.Local).AddTicks(9953),
                            UserId = 15
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 465, DateTimeKind.Local).AddTicks(9971),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 465, DateTimeKind.Local).AddTicks(9971),
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 465, DateTimeKind.Local).AddTicks(9987),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 465, DateTimeKind.Local).AddTicks(9987),
                            UserId = 9
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(4),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(4),
                            UserId = 10
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(21),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(21),
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(38),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(38),
                            UserId = 9
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(54),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(54),
                            UserId = 7
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(71),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(71),
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(88),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(88),
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(105),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(105),
                            UserId = 13
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(121),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(121),
                            UserId = 11
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(138),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(138),
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(155),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(155),
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(174),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(174),
                            UserId = 5
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(190),
                            IsLike = false,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(190),
                            UserId = 6
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(207),
                            IsLike = true,
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 466, DateTimeKind.Local).AddTicks(207),
                            UserId = 15
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvatarId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 439, DateTimeKind.Local).AddTicks(2040),
                            Email = "Elissa99@gmail.com",
                            Password = "2z4Q4fqp",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 439, DateTimeKind.Local).AddTicks(2040),
                            UserName = "Anderson_Koch76"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(3952),
                            Email = "Erna_Stiedemann31@gmail.com",
                            Password = "7ZBu20nv",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(3952),
                            UserName = "Carrie61"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(4461),
                            Email = "Jarrell.Yundt@gmail.com",
                            Password = "9ZwQOsGX",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(4461),
                            UserName = "Francis_Krajcik65"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(4704),
                            Email = "Cesar_Botsford31@hotmail.com",
                            Password = "ryq18hs1",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(4704),
                            UserName = "Garett_Halvorson"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(4858),
                            Email = "Oceane36@yahoo.com",
                            Password = "TmUDETOO",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(4858),
                            UserName = "Carey_Schoen48"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(5063),
                            Email = "Reid0@hotmail.com",
                            Password = "tgtz4nFg",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(5063),
                            UserName = "Raleigh13"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 9,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(5184),
                            Email = "Hassan84@hotmail.com",
                            Password = "glZffk91",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(5184),
                            UserName = "Xavier99"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(5302),
                            Email = "Hester_Orn@yahoo.com",
                            Password = "5keAm2rY",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(5302),
                            UserName = "Jaydon.Stehr44"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(5478),
                            Email = "Hank47@gmail.com",
                            Password = "VPvGsDiF",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(5478),
                            UserName = "Wilfrid71"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(5600),
                            Email = "Timothy_Mills@yahoo.com",
                            Password = "mO0gFA5K",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(5600),
                            UserName = "Talia.Kunde88"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(5829),
                            Email = "Regan_Weimann9@yahoo.com",
                            Password = "OVh4EnSH",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(5829),
                            UserName = "Rasheed95"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(5961),
                            Email = "Jayde_Barrows@yahoo.com",
                            Password = "2Jm9phJj",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(5961),
                            UserName = "Zelda73"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(6128),
                            Email = "Angelita_Carter41@gmail.com",
                            Password = "DB5cRJjT",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(6128),
                            UserName = "Arno.Simonis62"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 1,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(6264),
                            Email = "Evert_Harris@yahoo.com",
                            Password = "HvGH2UcJ",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(6264),
                            UserName = "Paige.Casper95"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(6485),
                            Email = "Nathanael80@gmail.com",
                            Password = "f5ZiH8rf",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(6485),
                            UserName = "Brian.Fisher54"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(6621),
                            Email = "Camryn34@gmail.com",
                            Password = "5zrvA3aC",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(6621),
                            UserName = "Emerson_Gutkowski"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(6748),
                            Email = "Odessa97@yahoo.com",
                            Password = "Qdoj3wE1",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(6748),
                            UserName = "Dixie.Marquardt34"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(6927),
                            Email = "Elouise4@gmail.com",
                            Password = "q7yx12PL",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(6927),
                            UserName = "Clara_Schuster43"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(7048),
                            Email = "Jarrett28@gmail.com",
                            Password = "ZK1STjgb",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(7048),
                            UserName = "Korbin_Veum34"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(7224),
                            Email = "Laverne.Altenwerth@hotmail.com",
                            Password = "cYvjloAx",
                            UpdatedAt = new DateTime(2019, 4, 2, 16, 21, 12, 447, DateTimeKind.Local).AddTicks(7224),
                            UserName = "Elliott78"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.Reaction", "Reaction")
                        .WithMany()
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Thread_.NET.DAL.Entities.Reaction", "Reaction")
                        .WithMany()
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Reaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
