import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
    MatToolbarModule,
    MatButtonModule,
    MatSidenavModule,
    MatIconModule,
    MatListModule,
    MatSelectModule,
    MatInputModule,
    MatAutocompleteModule,
    MatBadgeModule,
    MatCardModule,
    MatDatepickerModule,
    MatGridListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatTableModule,
    MatTabsModule,
    MatTooltipModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatChipsModule,
    MatPaginatorModule,
    MatCheckboxModule,
    MatExpansionModule,
    MatStepperModule,
    MatRadioModule,
    MatDialogModule,
    MatSnackBarModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatSortModule
} from '@angular/material';

@NgModule({
    imports: [
        CommonModule,
        MatToolbarModule,
        MatButtonModule,
        MatSidenavModule,
        MatIconModule,
        MatListModule,
        MatSelectModule,
        MatInputModule,
        MatAutocompleteModule,
        MatBadgeModule,
        MatCardModule,
        MatDatepickerModule,
        MatGridListModule,
        MatMenuModule,
        MatNativeDateModule,
        MatTableModule,
        MatTabsModule,
        MatTooltipModule,
        MatProgressBarModule,
        MatProgressSpinnerModule,
        MatChipsModule,
        MatPaginatorModule,
        MatCheckboxModule,
        MatExpansionModule,
        MatStepperModule,
        MatRadioModule,
        MatDialogModule,
        MatSnackBarModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatSortModule
    ],
    exports: [
        MatToolbarModule,
        MatButtonModule,
        MatSidenavModule,
        MatIconModule,
        MatListModule,
        MatSelectModule,
        MatInputModule,
        MatAutocompleteModule,
        MatBadgeModule,
        MatCardModule,
        MatDatepickerModule,
        MatGridListModule,
        MatMenuModule,
        MatNativeDateModule,
        MatTableModule,
        MatTabsModule,
        MatTooltipModule,
        MatProgressBarModule,
        MatProgressSpinnerModule,
        MatChipsModule,
        MatPaginatorModule,
        MatCheckboxModule,
        MatExpansionModule,
        MatStepperModule,
        MatRadioModule,
        MatDialogModule,
        MatSnackBarModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatSortModule
    ],
    declarations: []
})
export class MaterialComponentsModule {}
